name: RocketPluginHelper

on:
  create:
    tags:
      - "*"
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/RocketPluginHelper.yaml'
      - 'src/RocketPluginHelper/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/RocketPluginHelper.yaml'
      - 'src/RocketPluginHelper/**'

jobs:
  build:
    name: "RocketPluginHelper Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v3
      name: Setup .NET
      with:
        dotnet-version: 7.x
    - uses: ./.github/actions/project-build
      id: project-build
      with:
        project_path: src/RocketPluginHelper
        github_token: ${{ secrets.GITHUB_TOKEN }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true